### ISSUE TITLE
TcpServer中无法获取TcpSocket对象

### ISSUE THREAD

**Issue by liaoyudong2** [jwcpp/jwEngine#1]
从代码结构看 似乎是多用于单线程逻辑处理 对于多线程情况下 如何向指定TcpSocket发送消息? 从Server或者Event似乎都无法获取到Socket 对于服务器总不可能都是基于req响应吧...

**Comment by jwcpp** [comment]
socket对象指针需要逻辑层保存，框架只响应事件，不做其它处理

**Comment by liaoyudong2** [comment]
也就相当于框架只负责响应事件 上层负责对事件产生的对象进行维护? 这情况下对于整体关闭销毁的时候似乎只有uv_walk能关闭所有的handle 总不能由上层来负责销毁这些产物吧 如果上层遗忘销毁 那不就是内存泄露了?
这一块我是纠结了老久 一直在找别人是如何处理这种问题 参考 比对不同处理方式...

**Comment by jwcpp** [comment]
不用维护连接对象的生命周期，框架创建的对象，由框架自己回收。
具体看看这几个回调函数的堆栈执行顺序
createConnect()
destroyConnect(KcpSession * conn)
onAccept(NetConnect * conn)
onClose(NetConnect * conn)
