### ISSUE TITLE
load lua file error:server.lua:6: aligned allocation of userdata block (data section) for 'Lua_NetServer' failed

### ISSUE THREAD

**Issue by galenho** [jwcpp/jwEngine#2]
编译环境 Windows10, VS2019

执行example-->lua_tcp-->server.bat,  控制台显示以下错误
load lua file error:server.lua:6: aligned allocation of userdata block (data section) for 'Lua_NetServer' failed

这是什么原因？求助

**Comment by jwcpp** [comment]
sol2由develop分支切换到main分支，重新编译
