### ISSUE TITLE
win10 vs2019 c++17 c1001 内部编译器错误

### ISSUE THREAD

**Issue by lvshiling** [jwcpp/jwEngine#3]
![jp](https://user-images.githubusercontent.com/904846/113465731-15041c80-9469-11eb-807c-a0daecd74534.png)
![ep](https://user-images.githubusercontent.com/904846/113467109-70d3a300-9473-11eb-9d7d-94f961a33e58.png)

**Comment by jwcpp** [comment]
gutting the macro SOL_PROXY_BASE_IMPL_MSVC_IS_TRASH_I_

**Comment by lvshiling** [comment]
OK
